---

- name: install common dependencies
  yum: name={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - cmake
    - freetype-devel
    - gcc
    - gcc-c++
    - git
    - mercurial
    - libtool
    - make
    - mercurial
    - nasm
    - pkgconfig
    - zlib-devel
    - yasm

- name: make ffmpeg directory
  file: path={{ item }} state=directory owner={{ user_name }} group={{ user_name }} mode=0755
  with_items:
    - "{{ ffmpeg_source_dir }}"
    - "{{ ffmpeg_bin_dir }}"
    - "{{ ffmpeg_build_dir }}"

# Clone from GitRepository

- name: clone latest yasm
  git: >
    repo=https://github.com/yasm/yasm.git
    dest={{ ffmpeg_source_dir }}/yasm

- name: clone latest x264
  git: >
    repo=git://git.videolan.org/x264
    dest={{ ffmpeg_source_dir }}/x264
    accept_hostkey=true

- name: clone latest fdk-aac
  git: >
    repo=git://git.code.sf.net/p/opencore-amr/fdk-aac
    dest={{ ffmpeg_source_dir }}/fdk-aac
    accept_hostkey=true

- name: clone latest libopus
  git: >
    repo=git://git.opus-codec.org/opus.git
    dest={{ ffmpeg_source_dir }}/opus
    accept_hostkey=true

- name: clone latest libvpx
  git: >
    repo=https://chromium.googlesource.com/webm/libvpx.git
    dest={{ ffmpeg_source_dir }}/libvpx

- name: clone latest ffmpeg
  git: >
    repo=https://github.com/FFmpeg/FFmpeg.git
    dest={{ ffmpeg_source_dir }}/ffmpeg

# Clone from HgRepository

- name: clone latest x265
  hg: >
    repo=https://bitbucket.org/multicoreware/x265
    dest={{ ffmpeg_source_dir }}/x265

# Get source with url

- name: download libmp3lame
  get_url: >
    url=http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
    dest={{ ffmpeg_source_dir }}/lame-3.99.5.tar.gz

- name: download libogg
  get_url: >
    url=http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
    dest={{ ffmpeg_source_dir }}/libogg-1.3.2.tar.gz

- name: download libvorbis
  get_url: >
    url=http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.4.tar.gz
    dest={{ ffmpeg_source_dir }}/libvorbis-1.3.4.tar.gz

# Unarchive tar file

- name: unarchive libmp3lame
  unarchive: src={{ ffmpeg_source_dir }}/lame-3.99.5.tar.gz dest={{ ffmpeg_source_dir }} copy=no

- name: unarchive libogg
  unarchive: src={{ ffmpeg_source_dir }}/libogg-1.3.2.tar.gz dest={{ ffmpeg_source_dir }} copy=no

- name: unarchive libvorbis
  unarchive: src={{ ffmpeg_source_dir }}/libvorbis-1.3.4.tar.gz dest={{ ffmpeg_source_dir }} copy=no

# Compile

- name: compile yasm
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/yasm"
  with_items:
    - autoreconf -fiv
    - "./configure --prefix={{ ffmpeg_build_dir }}"
    - make
    - make install
    - make distclean

- name: compile libx264
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/x264"
  with_items:
    - "./configure --prefix={{ ffmpeg_build_dir }} --bindir={{ ffmpeg_bin_dir }} --enable-static"
    - make
    - make install
    - make distclean

- name: compile libx265
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/x265/build/linux"
  with_items:
    - 'cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="{{ ffmpeg_build_dir }}" -DENABLE_SHARED:bool=off ../../source'
    - make
    - make install

- name: compile libfdk_aac
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/fdk-aac"
  with_items:
    - autoreconf -fiv
    - "./configure --prefix={{ ffmpeg_build_dir }} --disable-shared"
    - make
    - make install
    - make distclean

- name: compile libmp3lame
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/lame-3.99.5"
  with_items:
    - "./configure --prefix={{ ffmpeg_build_dir }} --bindir={{ ffmpeg_bin_dir }} --disable-shared --enable-nasm"
    - make
    - make install
    - make distclean

- name: compile libopus
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/opus"
  with_items:
    - autoreconf -fiv
    - "./configure --prefix={{ ffmpeg_build_dir }} --disable-shared"
    - make
    - make install
    - make distclean

- name: compile libogg
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/libogg-1.3.2"
  with_items:
    - "./configure --prefix={{ ffmpeg_build_dir }} --disable-shared"
    - make
    - make install
    - make distclean

- name: compile libvorbis
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/libvorbis-1.3.4"
  with_items:
    - './configure --prefix="{{ ffmpeg_build_dir }}" --with-ogg="{{ ffmpeg_build_dir }}" --disable-shared LDFLAGS="-L{{ ffmpeg_build_dir }}/lib" CPPFLAGS="-I{{ ffmpeg_build_dir }}/include"'
    - make
    - make install
    - make distclean

- name: compile libvpx
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/libvpx"
  with_items:
    - "./configure --prefix={{ ffmpeg_build_dir }} --disable-examples"
    - make
    - make install
    - make distclean

- name: configure ffmpeg
  shell: >-
    cd {{ ffmpeg_source_dir }}/ffmpeg &&
    PKG_CONFIG_PATH={{ ffmpeg_build_dir }}/lib/pkgconfig:$PKG_CONFIG_PATH &&
    PKG_CONFIG_PATH={{ ffmpeg_build_dir }}/lib/pkgconfig ./configure --prefix={{ ffmpeg_build_dir }} --extra-cflags=-I{{ ffmpeg_build_dir }}/include --extra-ldflags=-L{{ ffmpeg_build_dir }}/lib --bindir={{ ffmpeg_bin_dir }} --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265

- name: compile ffmpeg
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/ffmpeg"
  with_items:
    - PKG_CONFIG_PATH="{{ ffmpeg_build_dir }}/lib/pkgconfig" ./configure --prefix="{{ ffmpeg_build_dir }}" --extra-cflags="-I{{ ffmpeg_build_dir }}/include" --extra-ldflags="-L{{ ffmpeg_build_dir }}/lib" --bindir="{{ ffmpeg_bin_dir }}" --pkg-config-flags="--static" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265
    - make
    - make install
    - make distclean

- name: synbolic link
  sudo: yes
  file: src={{ ffmpeg_bin_dir }}/ffmpeg dest=/usr/local/bin/ffmpeg owner=root group=root state=link
